### ISSUE TITLE
User Input Sanitization

### ISSUE THREAD

**Issue by Apexal** [Apexal/telestrations-backend#17]
While the game flow is 99% done right now and is pretty stable, there are probably a bunch of ways to crash this. Let's put strong validations/sanitizations on the backend including:
- [x] limit length of drawing strokes array to certain length
- [x] limit length of display names
- let's think of more...

**Comment by gmisail** [comment]
For the display names, shouldn't we make it as long as the longest randomly generated name? This way there won't be any conflicts (not that it is a big deal.)

**Comment by gmisail** [comment]
After doing some research, the longest possible name that can be generated by the backend is "old-fashioned affenpinscher", which is 26 characters, or 27 with a space.
